sudo: false
language: scala
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-M5
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION  clean coverage test
after_success:
  - sbt coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aef733c0903d3e0594f8
    on_success: change
    on_failure: always
    on_start: never
